---
services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - backend
  
  backend:
    build: ./airbnb-backend
    volumes:
      - ./airbnb-backend:/usr/src/airbnb_backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - database
  database:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=airbnb

volumes:
  postgres-data:
